apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: levelup-s3-rpa-CHANGE-ME
  labels:
    role: levelup-s3-rpa-CHANGE-ME
    crossplane-demo: levelup-managed-resources
spec:
  forProvider:
    policyArnRef:
      name: levelup-s3-crud-CHANGE-ME
    roleRef:
      name: levelup-s3-iam-role-CHANGE-ME