apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: x-vm-redis-postgres.demo.tm.io
  labels:
    demo.tm.io/option: vm-redis-postgres
spec:
  compositeTypeRef:
    apiVersion: demo.tm.io/v1alpha1
    kind: XVmDbCombo
  patchSets:
    - name: common
      patches:
        - fromFieldPath: spec.location
          toFieldPath: spec.location
        - fromFieldPath: spec.resourceGroup
          toFieldPath: spec.resourceGroup
  resources:
    - name: virtualMachine
      base:
        apiVersion: demo.tm.io/v1alpha1
        kind: XVirtualMachine
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.id
          toFieldPath: spec.id
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
    - name: redisDb
      base:
        apiVersion: demo.tm.io/v1alpha1
        kind: XDataBase
        spec:
          compositionSelector:
            matchLabels:
              demo.tm.io/option: redis
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.id
          toFieldPath: spec.id
          transforms:
            - type: string
              string:
                fmt: "%s-redis"
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-redis"
    - name: postgresDb
      base:
        apiVersion: demo.tm.io/v1alpha1
        kind: XDataBase
        spec:
          compositionSelector:
            matchLabels:
              demo.tm.io/option: postgres
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.id
          toFieldPath: spec.id
          transforms:
            - type: string
              string:
                fmt: "%s-postgres"
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-postgres"



