apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xazurestorages.levelup.upbound.io
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: levelup.upbound.io/v1alpha1
    kind: XAzureStorage
  resources:
  - base:
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
    name: resourceGroup
    patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: spec.id
        toFieldPath: metadata.labels["rg"]
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: spec.location
        toFieldPath: spec.forProvider.location
  - base:
      apiVersion: storage.azure.upbound.io/v1beta1
      kind: Account
      spec:
        forProvider:
          accountReplicationType: LRS
          accountTier: Standard
          resourceGroupNameSelector:
            matchControllerRef: true
    name: storageAccount
    patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels["rg"]
        transforms:
          - type: string
            string:
              fmt: "%s-rg"
      - fromFieldPath: spec.location
        toFieldPath: spec.forProvider.location
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%sstorageacc"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.tags.Name
        transforms:
          - type: string
            string:
              fmt: "%sstorageacc"
  - base:
      apiVersion: storage.azure.upbound.io/v1beta1
      kind: Container
      spec:
        forProvider:
          containerAccessType: blob
    name: storageAccountContainer
    patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.storageAccountNameRef.name
        transforms:
          - type: string
            string:
              fmt: "%sstorageacc"
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-container"