apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgcpbuckets.levelup.upbound.io
spec:
  group: levelup.upbound.io
  names:
    kind: XGcpBucket
    plural: xgcpbuckets
  claimNames:
    kind: GcpBucket
    plural: gcpbucketss
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: "Create resources for levelup training"
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: "base id prefix for all managed resources"
                location:
                  type: string
                  description: location
              required:
                - id
                - location