apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: levelup-rg-CHANGE-ME
  labels:
    demo.tm.io/landingzone: levelup-managed-resources
spec:
  forProvider:
    location: West US 3