apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: levelup-obj-CHANGE-ME
  labels:
    tm.demo.io/app: levelup-managed-resources
spec:
  managementPolicy: ObserveCreateUpdate
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: levelup-secret-CHANGE-ME
        namespace: default
      data:
        pword: VG1kZW1vMUAwQDMK #Tmdemo1@0@3
  providerConfigRef:
    name: kubernetes-provider