apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: tm-demo-1-obj
  labels:
    tm.demo.io/app: tm-demo-1
spec:
  managementPolicy: ObserveCreateUpdate
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: tm-demo-1-secret
        namespace: default
      data:
        pword: VG1kZW1vMUAwQDMK #Tmdemo1@0@3
  providerConfigRef:
    name: kubernetes-provider