apiVersion: network.azure.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: levelup-secgrp-CHANGE-ME
  labels:
    demo.tm.io/landingzone: levelup-managed-resources
spec:
  forProvider:
    location: West US 3
    resourceGroupNameRef:
      name: levelup-rg-CHANGE-ME