apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: levelup-subnet-CHANGE-ME
  labels:
    demo.tm.io/landingzone: levelup-managed-resources
spec:
  forProvider:
    resourceGroupNameRef:
      name: levelup-rg-CHANGE-ME
    virtualNetworkNameRef:
      name: levelup-vnet-CHANGE-ME
    addressPrefixes:
      - 192.168.1.0/24
    serviceEndpoints:
      - Microsoft.Sql