apiVersion: network.azure.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  name: levelup-vm-nic-CHANGE-ME
  labels:
    demo.tm.io/landingzone: levelup-managed-resources
spec:
  forProvider:
    ipConfiguration:
      - name: levelup-ip-config-CHANGE-ME
        privateIpAddressAllocation: Dynamic
        subnetIdRef:
          name: levelup-subnet-CHANGE-ME
    location: West US 3
    resourceGroupNameRef:
      name: levelup-rg-CHANGE-ME