apiVersion: compute.azure.upbound.io/v1beta1
kind: LinuxVirtualMachine
metadata:
  name: levelup-vm-CHANGE-ME
  labels:
    demo.tm.io/landingzone: levelup-managed-resources
spec:
  forProvider:
    adminUsername: adminuser
    disablePasswordAuthentication: false
    adminPasswordSecretRef:
      name: levelup-secret-CHANGE-ME
      namespace: default
      key: pword
    location: West US 3
    networkInterfaceIdsRefs:
      - name: levelup-vm-nic-CHANGE-ME
    osDisk:
      - caching: ReadWrite
        storageAccountType: Standard_LRS
    resourceGroupNameRef:
      name: levelup-rg-CHANGE-ME
    size: Standard_B1s
    sourceImageReference:
      - offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest