apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: levelup-vnet-CHANGE-ME
  labels:
    demo.tm.io/landingzone: levelup-managed-resources
spec:
  forProvider:
    resourceGroupNameRef:
      name: levelup-rg-CHANGE-ME
    location: West US 3
    addressSpace:
      - 192.168.0.0/16
